server:
  port: 5555

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: licensingservice
          uri: lb://licensingservice
          predicates:
            - Path=/licensing/**
        - id: organizationservice
          uri: lb://organizationservice
          predicates:
            - Path=/organization/**
